### ISSUE TITLE
Design na nowy system

### ISSUE THREAD

**Issue by marcinlawnik** [akai-org/rozklad-ekrany#2]
Wymiary: 1920x1080 (FullHD),

Na designie trzeba zmieścić 7 kierunków (politechnika x2, kórnicka x3, baraniaka x2).
Trzebaby pokazać graficznie którego przystanku który rozkład się tyczy.
Musi się też znaleźć miejsce na dwie ilości rowerów na stacjach (to co aktualnie jest na dole).
Dodatkowo fajnie by było jakby się zmieściło logo AKAI i KN ITP (koło naukowe inżynierów transportu publicznego).
Aktualny mniejszy design, zawiera dane które mają być pokazane (UWAGA, ekrany się zmieniają co 10-20s, w nowej wersji będzie tylko jeden ekran)
https://akai-org.github.io/rozklad-ekrany/

**Comment by tomaszgil** [comment]
![timetable](https://user-images.githubusercontent.com/17861616/46540492-d140f400-c8b9-11e8-8851-f4b1ba4b753e.png)
[timetable.zip](https://github.com/akai-org/rozklad-ekrany/files/2450646/timetable.zip)

Sugerowałbym jeszcze dla poprawy widoczności kolorować godzinę odjazdu konkretnego przejazdu na czerwono (jeśli tramwaj odjeżdża za mniej niż 3 minuty), na żółto (jeśli za mniej niż 7 minut), reszta zostałaby czarna. 

Paleta kolorów do tego:
czerwony: #DD0E0E
żółty: #D49A11

**Comment by marcjasz** [comment]
![przechwytywanie](https://user-images.githubusercontent.com/17887909/46632642-a5d53800-cb4b-11e8-8f9f-213519a8998e.PNG)

Muszę jeszcze tylko naprawić kolejność. Na pewno ma być 7 kierunków? Dostajemy informacje dla 5 kórnickich, czyli w sumie 9. Da się to wcisnąć, tylko trzeba zwęzić rozkładziki ofc. 

Trzeba by też wymyślić coś, żeby było dokładnie wiadomo, o który przystanek chodzi.

**Comment by roertbb** [comment]
Może dodanie informacji Baraniaka -> rondo Śródka / Baraniaka -> Kórnicka pozwoliłoby rozróżnić przystanki?

**Comment by marcjasz** [comment]
![przechwytywanie](https://user-images.githubusercontent.com/17887909/46920816-0d7bff00-cff4-11e8-8b0f-948f127e4fe1.PNG)

Wcisnęliśmy jeszcze dwa przystanki i ikonkę roweru. Michał zaproponował dodanie strzałek pokazujących kierunek każdego przystanku. IMO tak jest dużo czytelniej. Może być?
